// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ctx() {
  return window['go']['main']['App']['Ctx']();
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}
