// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCommand(arg1) {
  return window['go']['main']['DesktopEntries']['RunCommand'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['DesktopEntries']['Search'](arg1);
}
