// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCommand(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<string>;
